import { chromium } from 'playwright';
const url = 'https://thorough-shake-publication-grain.trycloudflare.com';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
await page.goto(url, { waitUntil: 'networkidle', timeout: 90000 });
await page.waitForTimeout(3000);
const text = await page.locator('.hero').innerText().catch(()=>'NO HERO');
const themes = await page.locator('.theme-chip').count();
const nums = await page.locator('.num').allTextContents();
await page.screenshot({ path: '/opt/cursor/artifacts/vakit-public.png', fullPage: true });
console.log(JSON.stringify({ url, errors, text, themes, nums }, null, 2));
await browser.close();
